# Generated by Django 5.2 on 2025-04-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='capacity',
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ManyToManyField(related_name='products', to='inventory.warehouse'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(related_name='products', to='inventory.supplier'),
        ),
    ]
